const conceito = [
    {
        title: 'Democracia',
        description: 'Democracia é um regime político em que todos os cidadãos elegíveis participam igualmente — diretamente ou através de representantes eleitos — na proposta, no desenvolvimento e na criação de leis, exercendo o poder da governação através do sufrágio universal. Ela abrange as condições sociais, econômicas e culturais que permitem o exercício livre e igual da autodeterminação política. O termo origina-se do grego antigo δημοκρατία (dēmokratía ou "governo do povo"),[1] que foi criado a partir de δῆμος (demos ou "povo") e κράτος (kratos ou "poder") no século V a.C. para denotar os sistemas políticos então existentes em cidades-Estados gregas, principalmente Atenas; o termo é um antônimo para ἀριστοκρατία (aristokratia ou "regime de uma aristocracia" como seu nome indica). Embora, teoricamente, estas definições sejam opostas, na prática, a distinção entre elas foi obscurecida historicamente.[2] No sistema político da Atenas Clássica, por exemplo, a cidadania democrática abrangia apenas homens, filhos de pai e mãe atenienses, livres e maiores de 21 anos, enquanto estrangeiros, escravos e mulheres eram grupos excluídos da participação política. Em praticamente todos os governos democráticos em toda a história antiga e moderna, a cidadania democrática valia apenas para uma elite de pessoas, até que a emancipação completa foi conquistada para todos os cidadãos adultos na maioria das democracias modernas através de movimentos por sufrágio universal durante os séculos XIX e XX.'
    },
    {
        title: 'Historiografia',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Absolutismo',
        description: 'O Absolutismo é um conceito histórico que se refere à forma de governo e que o poder é centralizado na figura do monarca, que o transmite hereditariamente. Esse sistema foi específico da Europa nos séculos xvi a xvii. Assim, não podemos falar de um Absolutismo chinês ou africano, pois devemos ter sempre em mente que osconceitos são construídos para determinado momento e lugar na história, e não podem ser aplicados para outras realidades de forma indiscriminada. O surgimento do Absolutismo se deu com a unificação dos Estados nacionaisna Europa ocidental no início da Idade Moderna, e foi realizada com a centralização de territórios, criação de burocracias, ou seja, centralização de poder nas mãos dos soberanos. Essa centralização aconteceu, no entanto, após uma série de conflitos específicos. Durante a Idade Média, os monarcas feudais dividiam o poder com os grandes senhores de terra, mas com a formação dos Estados nacionais iniciou-se um processo de diminuição do poder desses senhores. Tal processo foi possibilitado pelo crescente poder econômico da burguesia, uma camada social nascente que, sem  burguesia, característicos desse momento histórico, além das disputas políticas entre os príncipes e a Igreja Católica, visto que o Papado durante toda a Idade Média foi uma considerável força internacional. Nesse processo, é notável a ligação entre política e religião, pois o Absolutismo tendia a conceder ao rei um caráter sacralizado. Esse aspecto foi mais enfatizado naFrança pela teoria do direito divino dos reis, defendida no século xvii por filósofos como o bispo Bossuet. Uma teoria que legitimava o poder absoluto da monarquiafrancesa, cujo principal expoente foi Luís xiv, o chamado Rei Sol, defendendo que opoder absoluto do rei e a centralização do Estado se deviam a Deus. Deus escolhera o reie sua linhagem, e logo seu poder não deveria ser contestado por nenhum dos súditos.'
        
    },
    {
        title: 'Fascismo',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Socialismo',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Imperialismo',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Oligarquia',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Autarquia',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Baixa Idade Média',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Alta Idade Média',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Comunismo',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Capitalismo',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Estado',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Governo',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Liberdade',
        description: 'Se a História é uma ciência (cujo objecto é o homem no tempo), tem que submeter-se, como toda a ciência, ao método científico. Ainda que este não possa ser integralmente aplicado a todos os campos das ciências experimentais, pode-se fazê-lo a um nível equiparável ao das chamadas Ciências Sociais (ver: Método histórico, Metodologia e Metodologia nas ciências sociais). Um terceiro conceito confluente no momento de definir-se a História como fonte de conhecimento é a chamada Teoria da História, também denominada como "historiologia" (termo cunhado por José Ortega y Gasset)[2]), cujo papel é o de estudar a estrutura, leis e condições da realidade histórica (DRAE); enquanto que o da "historiografia" é o de relato em si mesmo da história, da arte de escrevê-la (DRAE).É impossível acabar com a polissemia e com a superposição destas três acepções, mas de maneira simplificada, pode-se admitir: a história é o estudo dos homens no tempo e seus feitos; a historiografia é a ciência da história e a historiologia a sua epistemologia.A Filosofia da História é o ramo da filosofia que concerne ao significado da história humana, se é que o tem. Especula acerca de um possível fim teleológico de seu desenvolvimento, ou seja, pergunta-se se há um esboço, um propósito, princípio director ou finalidade no processo da história humana. Não deve confundir-se com os três conceitos anteriores, dos quais se separa claramente. Se o seu objecto é a verdade ou o dever ser, se a história é cíclica ou linear, ou se nela existe a ideia de progresso, são matérias das quais trata esta disciplina, alheias à história e à historiografia propriamente ditas.Um enfoque intelectual, que tampouco contribui muito para entender a ciência histórica como tal, é a subordinação do ponto de vista filosófico à historicidade, considerando toda a realidade como produto de um devir histórico: esse seria o lugar do historicismo, corrente filosófica que pode estender-se a outras ciências, como a Geografia.Uma vez despojada da questão meramente nominal, resta para a historiografia, portanto, a análise da história escrita, das descrições do passado; especificamente dos enfoques na narração, interpretações, visões de mundo, uso das evidências ou documentos e os métodos de sua apresentação pelos historiadores; e também o estudo destes, por sua vez sujeitos e objectos da ciência.'
        
    },
    {
        title: 'Tempo',
        description: '4abcbc 9bcasbcub 5vcjdvasjchva 2djhcvasdvy 1hcasvdhca.4abcbc 9bcasbcub 5vcjdvasjchva 2djhcvasdvy 1hcasvdhca.'
    }
]

module.exports = conceito;